### ISSUE TITLE
Self-hosted version

### ISSUE THREAD

**Issue by iebb** [iebb/F1-Web-Viewer#1]
Check https://github.com/iebb/F1WebViewer-SelfHosted if you want to self-host the reverse proxy.

Currently the static assets are also proxied through netlify, and the login procedue is also routed through the public deta server, as the reese84 might be unstable.

**Comment by Tanguille** [comment]
Thanks for the efforts! Do you have any tutorial to configure this?

**Comment by iebb** [comment]
> Thanks for the efforts! Do you have any tutorial to configure this?

download [f1wvp-windows-amd64.exe](https://github.com/iebb/F1WebViewer-SelfHosted/releases/download/v0.0.1/f1wvp-windows-amd64.exe) from Releases, and run it

**Comment by derekgibson** [comment]
Just testing this on an m1 mac. watching fp2 with it. Lovely work, thanks!

**Comment by derekgibson** [comment]
> Just testing this on an m1 mac. watching fp2 with it. Lovely work, thanks!

Updating to say it working with live sessions too.

**Comment by Tanguille** [comment]
I still have a lot of buffering issues. Even with 1 stream on 720p. Original F1TV website doesn't have that. Any tips?

**Comment by iebb** [comment]
> I still have a lot of buffering issues. Even with 1 stream on 720p. Original F1TV website doesn't have that. Any tips?

Are you using self-hosted version? If true, try using Bitmovin Player from Settings Tab. It works on localhost without license, and it might be better for laggy networks

**Comment by Tanguille** [comment]
> 

Yep I am selfhosting it. My network should be pretty stable with constant download speeds of  100 Mbps. I'll give that a try. Thanks!
