### ISSUE TITLE
Will it be possible to play on vlc or mpv?

### ISSUE THREAD

**Issue by legowtham** [iebb/F1-Web-Viewer#5]
First of all thanks for the effort, much appreciated. I'm currently self-hosting and it works perfect on Live. 
Just an obligation, is it possible to play the stream on vlc or mpv? 
Since race control is broken due to DRM and can't play with the video players. 
Any help is appreciated, thanks :)

**Comment by iebb** [comment]
It won't, as DRM on windows platform is almost completely limited to browsers at the moment.
