### ISSUE TITLE
Cannot view video streams: "the media cannot be loaded..."

### ISSUE THREAD

**Issue by stinodp** [iebb/F1-Web-Viewer#8]
**Describe the bug**
Hi, I installed the F1-Web-Viewer on an Unbuntu VM (20.04.4 LTS). When I try to start a video stream, the media player shows: "The media could not be loaded, either because the server or network failed or because the format is not supported". I tried switching to Clappr, but I get a comparable error. I have the same issue with Chrome and Firefox.

**To Reproduce**
1. git clone https://github.com/iebb/F1-Web-Viewer.git
2. cd F1-Web-Viewer
3. npm install
4. npm run build
5. npm start
6. open a browser and navigate to http://x.x.x.x:3000/
7. logon
8. try to play any video

**Expected behavior**
The video should play without issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/105150380/167294615-0bde21a5-aa7d-4ddf-abd4-70fb5bb4a9b0.png)
![image](https://user-images.githubusercontent.com/105150380/167294841-cd423520-f49a-4437-a13b-8ed7eca51355.png)

**Desktop:**
 - OS: Windows 10 Pro (21H2)
 - Browser: Chrome version 101.0.4951.54 64bit, Firefox version 100.0 64bit
 - Version: Beta branch, commit c1b583a

**Server**
- OS: Unbuntu 20.04.4 LTS
- NPM: 8.8.0
- Virtualized on Hyper-V

**F1TV Account:**
 - Subscription Type: Pro
 - Country: Belgium

**Additional context**
When I check the Chrome debugging console, I can see the following error:
![image](https://user-images.githubusercontent.com/105150380/167294883-1f058be7-ee0f-412e-b9b8-32344180569f.png)

When trying to navigate directly to the proxy URL (for example: http://x.x.x.x:3000/proxy/https://ott-video-fer-cf.formula1.com/c8059.......), the server returns a 404 and the following message: "Not found because of proxy error: TypeError: headers.set-cookie[0].replaceAll is not a function"

**Comment by iebb** [comment]
does the reverse proxy-based one work? 
https://github.com/iebb/F1WebViewer-SelfHosted

running locally is not throughly tested, and might experience some issues. would looking into it later

**Comment by stinodp** [comment]
Yes, it does. I noticed something rather odd regarding that.

When I view a stream via the proxy-based one first, afterwards I can also view it from within this version, even when the proxy-based version isn't running anymore. This applies only for the specific streams I first opened via the proxy-based version. Aditionaly it also needs to be in the same browser, and the IP adres I host both versions on has to be the same (not the port). I suspect this has something to do with browser caching.

**Comment by iebb** [comment]
it does has caching headers, it's normal for browsers to cache that

**Comment by iebb** [comment]
@stinodp seems it's a cookie domain issue, just pushed a commit to fix it. try pulling again?

**Comment by stinodp** [comment]
I just tried the new commit, but unfortunately it does not resolve the issue. I also tried clearing my browser cache/cookies to make sure.

**Comment by iebb** [comment]
check server.js, line 79 however i'm unsure why headers['set-cookie'][0] is not set. (unable to replicate it)

**Comment by stinodp** [comment]
It turns out the headers were indeed set. There was however an issue with the replaceAll function. For some reason, replaceAll is not known on my system. I fixed this by using replace instead of replaceAll. Your previous fix was also necessary to get it working, tnx!

If replaced:

        const patched = headers['set-cookie'][0].replaceAll(
          "Path=", `Path=/proxy/${location.protocol}//${location.host}`
        ).replaceAll(
          /Domain=[^;]+/g, ''
        ).replaceAll(
          /SameSite=[^;]+/g, ''
        ).replaceAll(
          "Secure", ''
        ).replaceAll(
          /;+/g, ';'
        )

with:

         const patched = headers['set-cookie'][0].replace(
          /Path=/g, `Path=/proxy/${location.protocol}//${location.host}`
        ).replace(
          /Domain=[^;]+/g, ''
        ).replace(
          /SameSite=[^;]+/g, ''
        ).replace(
          "Secure", ''
        ).replace(
          /;+/g, ';'
        )

Everything seems to be working fine now.

**Comment by iebb** [comment]
> It turns out the headers were indeed set. There was however an issue with the replaceAll function. For some reason, replaceAll is not known on my system. I fixed this by using replace instead of replaceAll. Your previous fix was also necessary to get it working, tnx!
> 
> If replaced:
> 
> ```
>     const patched = headers['set-cookie'][0].replaceAll(
>       "Path=", `Path=/proxy/${location.protocol}//${location.host}`
>     ).replaceAll(
>       /Domain=[^;]+/g, ''
>     ).replaceAll(
>       /SameSite=[^;]+/g, ''
>     ).replaceAll(
>       "Secure", ''
>     ).replaceAll(
>       /;+/g, ';'
>     )
> ```
> 
> with:
> 
> ```
>      const patched = headers['set-cookie'][0].replace(
>       /Path=/g, `Path=/proxy/${location.protocol}//${location.host}`
>     ).replace(
>       /Domain=[^;]+/g, ''
>     ).replace(
>       /SameSite=[^;]+/g, ''
>     ).replace(
>       "Secure", ''
>     ).replace(
>       /;+/g, ';'
>     )
> ```
> 
> Everything seems to be working fine now.

That's pretty strange, but for compatibility I'm changing this
